# Generated by Django 5.0.9 on 2024-09-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(verbose_name="Дата и время привычки"),
        ),
    ]
